version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        VARIANT: 14
    command: /bin/sh -c "while sleep 1000; do :; done"  
    volumes:
      - ..:/workspace:cached
    environment:  
      PG_URL: postgres://shortcut:shortcut@database:5432/shortcut

  database:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: shortcut
      POSTGRES_USER: shortcut
      POSTGRES_DB: shortcut

  adminer:
    image: adminer:latest
    ports:
      - 8080:8080